// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo69XSLB9wh262f294sunpf9TtuUxFfxY',
    appId: '1:987622120836:web:7960861089b96714b411d1',
    messagingSenderId: '987622120836',
    projectId: 'bootcamp-app-firebase',
    authDomain: 'bootcamp-app-firebase.firebaseapp.com',
    storageBucket: 'bootcamp-app-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxvAYdLCHvr9HaO4s5OD7yvb0CJM6-YI',
    appId: '1:987622120836:android:be445c49cb6db493b411d1',
    messagingSenderId: '987622120836',
    projectId: 'bootcamp-app-firebase',
    storageBucket: 'bootcamp-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElKRpHnekmHCoL96Ao_3Wg56lpW5IE5I',
    appId: '1:987622120836:ios:e2b24fe4648d156db411d1',
    messagingSenderId: '987622120836',
    projectId: 'bootcamp-app-firebase',
    storageBucket: 'bootcamp-app-firebase.appspot.com',
    iosBundleId: 'com.example.bootcampApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAElKRpHnekmHCoL96Ao_3Wg56lpW5IE5I',
    appId: '1:987622120836:ios:e2b24fe4648d156db411d1',
    messagingSenderId: '987622120836',
    projectId: 'bootcamp-app-firebase',
    storageBucket: 'bootcamp-app-firebase.appspot.com',
    iosBundleId: 'com.example.bootcampApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo69XSLB9wh262f294sunpf9TtuUxFfxY',
    appId: '1:987622120836:web:a04c198b46e25c51b411d1',
    messagingSenderId: '987622120836',
    projectId: 'bootcamp-app-firebase',
    authDomain: 'bootcamp-app-firebase.firebaseapp.com',
    storageBucket: 'bootcamp-app-firebase.appspot.com',
  );
}
